config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  root 'tzeets#index'
  match '/users', to: 'users#index', via: 'get'
  # devise_for :users, :path_prefix => 'd'
  resources :tzeets
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'register', to: 'devise/registrations#new'

  end

  resources :users, :only =>[:show]
  match '/users/:id', to: 'users#show', via: 'get'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tzeet.rb
class Tzeet < ApplicationRecord
  belongs_to :user

  validates :user, :presence => true
  validates :text, :presence => true


  scope :recent, -> {order(created_at: :desc).limit(20)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  has_many :tzeets

  attr_accessor :login

  validates :username,
            :presence => true,
            :uniqueness => {
                :presence => true,
                :case_sensitive => false
            }

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def require_admin
    unless current_user&.admin
      redirect_to root_path, alert: 'Not permitted'
    end
  end

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/tzeets_controller.rb
class TzeetsController < ApplicationController
  before_action :set_tzeet, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :create]

  # before_action :authenticate_user!

  # GET /tzeets
  def index
    @tzeets = Tzeet.all.recent
    @tzeet = Tzeet.new
  end

  # GET /tzeets/1
  def show
  end

  # GET /tzeets/new
  def new
    @tzeet = Tzeet.new
  end

  # GET /tzeets/1/edit
  def edit
  end

  # POST /tzeets
  # POST /tzeets.json
  def create
    @tzeet = Tzeet.new(tzeet_params)
    if current_user #because of rspec problems..
      @tzeet.user = current_user
    end
    respond_to do |format|
      if @tzeet.save
        format.html { redirect_to root_path, notice: 'Tzeet was successfully created.' }
        format.json { render :show, status: :created, location: @tzeet }
      else
        format.html { render :new }
        format.json { render json: @tzeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tzeets/1
  # PATCH/PUT /tzeets/1.json
  def update
    respond_to do |format|
      if @tzeet.update(tzeet_params)
        format.html { redirect_to @tzeet, notice: 'Tzeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tzeet }
      else
        format.html { render :edit }
        format.json { render json: @tzeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tzeets/1
  # DELETE /tzeets/1.json
  def destroy
    unless @tzeet.user == current_user
      redirect_to root_path
    end
    @tzeet.destroy
    respond_to do |format|
      format.html { redirect_to tzeets_url, notice: 'Tzeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tzeet
      @tzeet = Tzeet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tzeet_params
      params.require(:tzeet).permit(:text, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin, only: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tzeets_helper.rb
module TzeetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/tzeets"  Twuzu
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="/tzeets"  Tzeets
      ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          li
            a href="/login"  login
          li
            a href="/register" register
        - else
          -if current_user&.admin
            li
              = link_to 'all users', users_path
          li
            =link_to current_user.username, current_user
          li
            = link_to 'Edit user details', edit_user_registration_path
          li
            a href="/logout"  Logout

app/views/layouts/application.html.slim
/doctype html
html
  head
    title Twuzu
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"
    = csrf_meta_tags
    == javascript_include_tag 'application', 'data-turbolinks-eval': false
    link href="https://fonts.googleapis.com/css?family=Pacifico" rel='stylesheet'
    = stylesheet_link_tag 'application', media: 'all', '' => 'reload'


  body
    = render 'layouts/header'
    div.container
      - if flash[:notice]
        div.alert.alert-info
          = flash[:notice]
      - if flash[:alert]
        div.alert.alert-danger
          = flash[:alert]
  div.container
    = yield

app/views/tzeets/_form.html.slim
- if current_user
  h4 Compose a tzeet
  = form_for @tzeet do |f|
    .field
      = f.text_area :text, autofocus: true, :class => 'form-control', :placeholder => 'What\'s on your mind?'
    = f.hidden_field :user_id, :value => current_user.id
    .actions
      = f.submit 'Tzeet it!', :class => 'btn'

app/views/tzeets/_list.html.slim
h4 Recent Tzeets
ul.list-group#tzeet-list
  - tzeets.each do |tzeet|
    li.list-group-item.individual-tzeet
      b
        - if tzeet.user
          = link_to tzeet.user.username, tzeet.user
        - else
            | [deleted]
      small
        = time_ago_in_words tzeet.created_at
      br
      = tzeet.text
      br
        /= link_to 'Show', tzeet
        /= link_to 'Edit', edit_tzeet_path(tzeet)
        /= link_to 'Destroy', tzeet, data: {confirm: 'Are you sure?'}, method: :delete

app/views/tzeets/edit.html.slim
h1 Editing tzeet

== render 'form'

= link_to 'Show', @tzeet
'  |
= link_to 'Back', tzeets_path

app/views/tzeets/index.html.slim
== render 'form'

== render 'list', tzeets: @tzeets

app/views/tzeets/new.html.slim
h1 New tzeet

== render 'form'

= link_to 'Back', tzeets_path

app/views/tzeets/show.html.slim
p#notice = notice

p
  strong Text:
  = @tzeet.text
p
  strong User:
  = @tzeet.user

= link_to 'Edit', edit_tzeet_path(@tzeet)
'  |
= link_to 'Back', tzeets_path

app/views/users/index.html.slim
h1 Users
ul
  - @users.each do |user|
    li
      = link_to user.username, user

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/users/show.html.slim
h4
  = @user.username
  span.label.label-success
    = "#{pluralize(@user.tzeets.count, 'tzeet')}"
br
== render 'tzeets/list', tzeets: @user.tzeets.recent